---
- hosts: gluster
  tasks:
    - name: Install btrfs-progs
      pacman: name=btrfs-progs state=present
      tags: packages

    - name: Install glusterfs
      pacman: name=glusterfs state=present
      tags: packages

    - name: Install rpcbind
      pacman: name=rpcbind state=present
      tags: packages

    - name: Create directories
      file: path={{ item }} state=directory mode=0775
      with_items:
        - "{{ glusterfs_brick_path }}"
        - "{{ glusterfs_mount_path }}"
      tags: dirs

    - name: Enable glusterd
      service: name=glusterd state=started enabled=yes
      tags: service


    - name: Configure the glusterfs volume
      gluster_volume:
        state: present
        name: "{{ glusterfs_vol_name }}"
        brick: "{{ glusterfs_brick_path }}"
        replicas: 3
        cluster: "{{ groups.gluster | join(',') }}"
        host: "{{ inventory_hostname }}"
        force: yes
      run_once: true
      tags: volume

    - name: Mount the glusterfs volume
      mount:
        name: "{{ glusterfs_mount_path }}"
        src: "{{ inventory_hostname }}:/{{ glusterfs_vol_name }}"
        fstype: glusterfs
        opts: defaults,_netdev
        state: mounted
      tags: mount
