---
- hosts: gluster
  tasks:
    - name: Install git
      pacman: name=git state=present
      tags: packages

    - name: Install ethtool
      pacman: name=ethtool state=present
      tags: packages

    - name: Set up smb.conf
      copy: src=smb.conf dest=/etc/samba/smb.conf
      tags: conf

    - name: Make sure smbpasswd directory exists
      file: path=/var/lib/samba/private state=directory mode=0700
      tags: paths

    - name: Copy over the ctdb directory
      copy: src=ctdb dest=/etc
      tags: conf

    - name: Make sure sysconfig directory exists
      file: path=/etc/sysconfig state=directory
      tags: paths

    - name: Copy over the sysconfig file
      copy: src=ctdb.sysconfig dest=/etc/sysconfig/ctdb
      tags: conf

    - name: Copy the systemctl file for ctdb
      copy: src=ctdb.service dest=/usr/lib/systemd/system/
      tags: conf

    - name: Roll out fixed ctdbd_wrapper script
      copy: src=ctdbd_wrapper dest=/usr/bin/ctdbd_wrapper mode=0755
      tags: paths
